In [7]:
import torch

In [8]:
# Tensor filled with uninitialized data
a = torch.empty(1)        # Single-element tensor
val = a.item()            # Value of that tensor
b = torch.empty(5)        # Vector of lenght 5 as tensor
c = torch.empty(3, 4)     # 3x4 matrix as tensor
d = torch.empty(2,2,2,3)  # 4 dim tensor
print(a)
print(val)
print(b)
print(c)
print(type(d))

tensor([4.8591e-26])
4.859136657128551e-26
tensor([4.8592e-26, 4.4829e-41, 1.4214e-33, 0.0000e+00, 1.5277e-23])
tensor([[7.5841e-34, 1.7096e-43, 1.1757e-35, 7.5833e-34],
        [1.1756e-35, 7.5833e-34, 1.7096e-43, 4.1170e-42],
        [3.7583e-42, 4.1170e-42, 3.7583e-42, 4.8387e-42]])
<class 'torch.Tensor'>


In [9]:
d = torch.zeros(2, 4)    # Tensor filled with value 0
e = torch.ones(2, 4)     # Tensor filled with value 1
print(d)
print(e)

data = [[1, 2, 3],[4, 5, 6]]
x_data = torch.tensor(data)    # Tensor from list
print(x_data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
x = torch.rand(3, 5)  # Tensor filled with random numbers from a uniform distribution on [0, 1)
print(x)
print(x.dtype)

y = torch.randint(1, 100, (3, 5))  # Tensor filled with random integers generated uniformly from [low, high)
print(y)
print(x.dtype)

tensor([[0.6117, 0.8653, 0.6500, 0.1106, 0.7379],
        [0.2284, 0.5667, 0.8635, 0.6502, 0.2021],
        [0.4684, 0.4033, 0.9139, 0.5837, 0.2244]])
torch.float32
tensor([[68, 70, 14, 11, 65],
        [ 1, 31, 52, 60, 93],
        [13, 75, 65, 95,  9]])
torch.float32


In [11]:
print(x.size())
print(x.shape)

torch.Size([3, 5])
torch.Size([3, 5])


In [ ]:
'''
PyTorch has 12 different data types:

torch.bool

torch.uint8
torch.int8
torch.int16 (torch.short)
torch.int32 (torch.int)
torch.int64 (torch.long)

torch.bfloat16
torch.float16 (torch.half)
torch.float32 (torch.float)
torch.float64 (torch.double)

torch.complex64 (torch.cfloat)
torch.complex128 (torch.cdouble)
'''

In [13]:
# Specify data types
b = torch.ones(5, dtype=torch.bool)
print(b)
c = torch.ones(5, dtype=torch.int32)
print(c)
x = torch.rand(5, dtype=torch.float16)
print(x)
x = torch.rand(5, dtype=torch.torch.bfloat16)
print(x)


tensor([True, True, True, True, True])
tensor([1, 1, 1, 1, 1], dtype=torch.int32)
tensor([0.6943, 0.6880, 0.2866, 0.0576, 0.6147], dtype=torch.float16)
tensor([0.7578, 0.4961, 0.2617, 0.6523, 0.1641], dtype=torch.bfloat16)


In [14]:
t = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(t)
print(f"First row: {t[0, :]}")         # Or simply t[0]
print(f"First column: {t[:, 0]}")
print(f"Last row: {t[-1, ...]}")
print(f"Last column: {t[..., -1]}")

t[:, 2] = 0
print(t)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
First row: tensor([1, 2, 3, 4])
First column: tensor([ 1,  5,  9, 13])
Last row: tensor([13, 14, 15, 16])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  2,  0,  4],
        [ 5,  6,  0,  8],
        [ 9, 10,  0, 12],
        [13, 14,  0, 16]])


In [15]:
x = torch.randint(-5, 6, (2, 2))
y = torch.randint(-5, 6, (2, 2))
print(x)
print(y)

# Element-wise operations
z1 = x + y;  z1 = torch.add(x, y)
z2 = x - y;  z2 = torch.sub(x, y)
z3 = x * y;  z3 = torch.mul(x, y)
z4 = x / y;  z4 = torch.div(x, y)

print("Add:", z1)
print("Sub:", z2)
print("Mul:", z3)
print("Div:", z4)

y.add_(x)    # y += x
y.sub_(x)    # y -= x
y.mul_(x)    # y *= x
#y.div_(x)    # y /= x

tensor([[ 2,  1],
        [ 0, -5]])
tensor([[-1, -4],
        [-4, -3]])
Add: tensor([[ 1, -3],
        [-4, -8]])
Sub: tensor([[ 3,  5],
        [ 4, -2]])
Mul: tensor([[-2, -4],
        [ 0, 15]])
Div: tensor([[-2.0000, -0.2500],
        [-0.0000,  1.6667]])


tensor([[-2, -4],
        [ 0, 15]])

In [16]:
x = torch.randint(-5, 6, (2, 3), dtype=torch.int32)
y = torch.randint(-5, 6, (3, 2), dtype=torch.int32)
print(x)
print(y)

# Matrix multiplication
z1 = x @ y
z2 = x.matmul(y)
z3 = torch.empty(2, 2, dtype=torch.int32)
torch.matmul(x, y, out=z3)
print(z1)
print(z2)
print(z3)
torch.testing.assert_close(z1, z2)
torch.testing.assert_close(z1, z3)

tensor([[ 3,  0,  1],
        [-2,  0, -1]], dtype=torch.int32)
tensor([[-4,  5],
        [ 3, -4],
        [ 2, -3]], dtype=torch.int32)
tensor([[-10,  12],
        [  6,  -7]], dtype=torch.int32)
tensor([[-10,  12],
        [  6,  -7]], dtype=torch.int32)
tensor([[-10,  12],
        [  6,  -7]], dtype=torch.int32)


In [17]:
x = x = torch.randint(-5, 6, (3, 4), dtype=torch.int32)    # 3 x 4 = 12
x1 = x.view(2, 6)         # 2 x 6 = 12
x2 = x.view(12)           # 12
print(x)
print(x1)
print(x2)

x = torch.arange(16)      # Tensor filled with 0, 1, ..., 15
y = x.view(2, -1)         # -1 will be changed to 8, 2 x 8 = 16
print('\n', x)
print(y)

tensor([[-2,  2, -4, -2],
        [ 1,  2,  4, -3],
        [-3,  4, -5, -3]], dtype=torch.int32)
tensor([[-2,  2, -4, -2,  1,  2],
        [ 4, -3, -3,  4, -5, -3]], dtype=torch.int32)
tensor([-2,  2, -4, -2,  1,  2,  4, -3, -3,  4, -5, -3], dtype=torch.int32)

 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])


In [18]:
x = torch.rand(1, 3)
x = x.to("cpu")         # Move tensor to CPU device
print(x)
x = x.to("cuda")        # Move tensor to GPU device
print(x)

dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
y = torch.rand(1, 3).to(dev)    # Move tensor to GPU, if available
print(y)

z = torch.rand(1, 3, device="cuda")    # Create tensor on GPU
print(z)

tensor([[0.9966, 0.0407, 0.8454]])
tensor([[0.9966, 0.0407, 0.8454]], device='cuda:0')
tensor([[0.9462, 0.4413, 0.7053]], device='cuda:0')
tensor([[0.1539, 0.8222, 0.8198]], device='cuda:0')


In [19]:
x = torch.randn(3, requires_grad=True)
print(x)       # Created by the user, grad_fn is None
print(x.grad_fn)
y = 2*x + 3    # y is created as a result of operations, so it has a grad_fn
print(y)
print(y.grad_fn)

tensor([-0.8743,  1.2765, -1.3801], requires_grad=True)
None
tensor([1.2513, 5.5529, 0.2398], grad_fn=<AddBackward0>)


In [20]:
a = torch.randn(2, 2)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

a = torch.randn(2, 2, requires_grad=True)
b = a.detach()    # New tensor with the same content but no gradient computation
print("a.requires_grad:", a.requires_grad)
print("b.requires_grad:", b.requires_grad)

with torch.no_grad():
    b = a**2 + 1
    print(b.requires_grad)

False
True
a.requires_grad: True
b.requires_grad: False
False


In [21]:
print(x.grad)
y.backward(x)    # backward() _accumulates_ the gradient for this tensor into .grad attribute
print(x.grad)    # dy/dx

None
tensor([-1.7487,  2.5529, -2.7602])
