<a href="https://colab.research.google.com/github/oleg0x/Python_libraries_examples/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The core feature of NumPy is its ndarray object — a powerful N-dimensional array that allows storage and manipulation of large datasets in memory more efficiently than standard Python lists.

Homogeneous: All elements must be of the same data type (e.g., float, int, bool).

Fixed-size: Unlike Python lists, NumPy arrays have a fixed size at creation.

Memory-efficient: Takes less space than Python lists due to contiguous memory al

In [2]:
import numpy as np

    numpy.linalg — операции линейной алгебры (простое умножение векторов и матриц есть в базовом варианте);
    numpy.random — функции для работы со случайными величинами;
    numpy.fft — прямое и обратное преобразование Фурье.


In [ ]:
def get_numeric_types_dynamically():
    """Dynamically find numeric types in NumPy 2.0+"""
    numeric_types = {
        'Integer': [],
        'Unsigned Integer': [],
        'Float': [],
        'Complex': [],
    }
    for name in dir(np):
        dtype = getattr(np, name)
        if not isinstance(dtype, type):
            continue
        if name.startswith('int'):
            numeric_types['Integer'].append(dtype)
        elif name.startswith('uint'):
            numeric_types['Unsigned Integer'].append(dtype)
        elif name.startswith('float'):
            numeric_types['Float'].append(dtype)
        elif name.startswith('complex'):
            numeric_types['Complex'].append(dtype)
    return numeric_types

get_numeric_types_dynamically()

# Also: bool, bytes, str, void

{'Integer': [numpy.int16,
  numpy.int32,
  numpy.int64,
  numpy.int8,
  numpy.int64,
  numpy.int32,
  numpy.integer,
  numpy.int64],
 'Unsigned Integer': [numpy.uint64,
  numpy.uint16,
  numpy.uint32,
  numpy.uint64,
  numpy.uint8,
  numpy.uint32,
  numpy.uint64],
 'Float': [numpy.longdouble,
  numpy.float16,
  numpy.float32,
  numpy.float64,
  numpy.floating],
 'Complex': [numpy.complex128,
  numpy.clongdouble,
  numpy.complex64,
  numpy.complexfloating]}

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')    # From lists
A

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
B = np.zeros((3, 4), 'float16')
print(B, B.dtype)

C = np.zeros_like(A, 'int8')    # The same size as A
print(C, C.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float16
[[0 0 0]
 [0 0 0]] int8


In [ ]:
B = np.ones((3, 4), 'float32')
print(B, B.dtype)

C = np.ones_like(A, 'bool')     # The same size as A
print(C, C.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float32
[[ True  True  True]
 [ True  True  True]] bool


In [ ]:
E = np.eye(3, dtype=np.int16)   # Identity matrix
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [98]:
beg = 2.5
end = 7
step = 0.5
B = np.arange(start=2.5, stop=7, step=0.5)
B

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [101]:
A = np.linspace(start=10, stop=50, num=12)
A

array([10.        , 13.63636364, 17.27272727, 20.90909091, 24.54545455,
       28.18181818, 31.81818182, 35.45454545, 39.09090909, 42.72727273,
       46.36363636, 50.        ])

In [ ]:
B = A.astype('str')             # Returns a new array
B

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')

M = A                           #Shallow copy
M[0, 1] *= 100
print("M =", M, M.dtype)
print("A =", A, A.dtype)
print(A == M, '\n')

N = A.copy()                    # Deep copy
N[0, 2] *= 100
print("N =", N, N.dtype)
print("A =", A, A.dtype)
print(A == N)

M = [[  1 200   3]
 [  4   5   6]] int32
A = [[  1 200   3]
 [  4   5   6]] int32
[[ True  True  True]
 [ True  True  True]] 

N = [[  1 200 300]
 [  4   5   6]] int32
A = [[  1 200   3]
 [  4   5   6]] int32
[[ True  True False]
 [ True  True  True]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')
print(A[0][2], A[0, 2])         # The same
print(A[1], A[1, :])            # The same
print(A[:, 1])
print("Last element:", A[-1][-1])
print("Last row:", A[-1])
print("Last column:", A[:, -1])
print("Columns in reverse order:", A[:, -1], A[:, -2], A[:, -3])

3 3
[4 5 6] [4 5 6]
[2 5]
Last element: 6
Last row: [4 5 6]
Last column: [3 6]
Columns in reverse order: [3 6] [2 5] [1 4]


In [ ]:
A = np.arange(10)
print(A)
print(A[[0, 4, -1]])            # Select specified elements by index

beg = 1; end = 8; step = 2
print(A[beg:end:step])          # Select from [beg, end) with step
print(A[2:6])                   # By default, step = 1
print(A[:5], A[5:])

[0 1 2 3 4 5 6 7 8 9]
[0 4 9]
[1 3 5 7]
[2 3 4 5]
[0 1 2 3 4] [5 6 7 8 9]


In [ ]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B = A[::-1]                     # From last to first
C = A[:, ::-1]                  # Take all elements, from last to first inside
print(A)
print(B)
print(C)

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]]
[[4 3 2 1]
 [8 7 6 5]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[False, False, True], [ True, False, True]])
A[I]

array([3, 4, 6])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[False, True, False], [False, True, False]])      # Indexing array
A[I] = 100
A

array([[  1, 100,   3],
       [  4, 100,   6]])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

I1 = np.array([[False, False, True], [True, False, True]])
I2 = np.array([[False, True, False], [False, False, True]])

B = A.copy();  C = A.copy();  D = A.copy()

B[np.logical_and(I1, I2)] = 100
C[np.logical_or(I1, I2)] = 100
D[np.logical_not(I1)] = 100

print('B:\n', B)
print('\nC:\n', C)
print('\nD:\n', D)

B:
 [[  1   2   3]
 [  4   5 100]]

C:
 [[  1 100 100]
 [100   5 100]]

D:
 [[100 100   3]
 [  4 100   6]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('A before:\n', A)

I = A > 3
print('I:\n', I)

A[np.logical_or(A < 2, A > 4)] = 100
print('A after:\n', A)

A before:
 [[1 2 3]
 [4 5 6]]
I:
 [[False False False]
 [ True  True  True]]
A after:
 [[100   2   3]
 [  4 100 100]]


In [ ]:
A = np.arange(24)
B = A.reshape(4, 6)             # 4 * 6 = 24
C = A.reshape(2, 3, 4)          # 2 * 3 * 4 = 24
# These are different representations of the same data
C[0, 0, 0] = -1
print('A:\n', A)
print('\nB:\n', B)
print('\nC:\n', C)

A:
 [-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

B:
 [[-1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

C:
 [[[-1  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.reshape(3, 2))
print(A.reshape(6, 1))
print(A.reshape(1, 6))
print(A.ravel())

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


In [ ]:
A = np.arange(24)
B = A.reshape(-1, 6)            # -1 means "calculate automatically"
C = A.reshape(4, -1, 2)         # -1 means "calculate automatically"
print(B.shape, C.shape)

(4, 6) (4, 3, 2)


In [ ]:
A = np.arange(12)
B = A.reshape(3, 4)
print(B)
print("Size:", B.size)
print("Dim:", B.ndim)
print("Shape:", B.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Size: 12
Dim: 2
Shape: (3, 4)


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.T                         # Matrix transposition
B = np.transpose(A)             # Matrix transposition
B = np.swapaxes(A, 0, 1)
print('A:\n', A)
print('B:\n', B)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.stack((A, B), axis=0)        # Join arrays along a new axis
D = np.stack((A, B), axis=1)        # Join arrays along a new axis

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]] 
Shape: (2, 3, 3) 

[[[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]] 
Shape: (3, 2, 3)


In [ ]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.concatenate((A, B), 0)       # Joins arrays along an existing axis
D = np.concatenate((A, B), 1)       # Joins arrays along an existing axis

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]] 
Shape: (6, 3) 

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 
Shape: (3, 6)


In [3]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.vstack((A, B))               # Stacks arrays vertically (row-wise)
D = np.hstack((A, B))               # Stacks arrays horizontally (column-wise)

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]] 
Shape: (6, 3) 

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 
Shape: (3, 6)


In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.repeat(A, 4)
print(B, '\n')

C = B.reshape(A.shape[0], A.shape[1], -1)
print(C)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6] 

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [15]:
A = np.array([[-1, 2, 3], [4, 5, 6], [7, 8, 9]], np.float32)
b = -2.

# Element-wise operations with matrix and number
C = A + b
D = A - b
E = A * b
F = A / b
G = A ** b

print('+\n', C, '\n')
print('-\n', D, '\n')
print('*\n', E, '\n')
print('/\n', F, '\n')
print('**\n', G, '\n')

+
 [[-3.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

-
 [[ 1.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] 

*
 [[  2.  -4.  -6.]
 [ -8. -10. -12.]
 [-14. -16. -18.]] 

/
 [[ 0.5 -1.  -1.5]
 [-2.  -2.5 -3. ]
 [-3.5 -4.  -4.5]] 

**
 [[1.         0.25       0.11111111]
 [0.0625     0.04       0.02777778]
 [0.02040816 0.015625   0.01234568]] 



In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'float32')
B = np.array([-1, 2, 1], 'float32')

# Element-wise operations with matrix and vector
C = A + B
D = A - B
E = A * B
F = A / B
G = A ** B

print('+\n', C, '\n')
print('-\n', D, '\n')
print('*\n', E, '\n')
print('/\n', F, '\n')
print('**\n', G)

+
 [[ 0.  4.  4.]
 [ 3.  7.  7.]
 [ 6. 10. 10.]] 

-
 [[2. 0. 2.]
 [5. 3. 5.]
 [8. 6. 8.]] 

*
 [[-1.  4.  3.]
 [-4. 10.  6.]
 [-7. 16.  9.]] 

/
 [[-1.   1.   3. ]
 [-4.   2.5  6. ]
 [-7.   4.   9. ]] 

**
 [[ 1.          4.          3.        ]
 [ 0.25       25.          6.        ]
 [ 0.14285715 64.          9.        ]]


In [14]:
A = np.array([[-1, 2, 3], [4, 5, 6], [7, 8, 9]], 'float32')
B = np.array([[1, -2, -3], [7, 8, 9], [4, 5, 6]], 'float32')

# Element-wise operations with matrices
C = A + B
D = A - B
E = A * B
F = A / B
G = A ** B

print('+\n', C, '\n')
print('-\n', D, '\n')
print('*\n', E, '\n')
print('/\n', F, '\n')
print('**\n', G)

+
 [[ 0.  0.  0.]
 [11. 13. 15.]
 [11. 13. 15.]] 

-
 [[-2.  4.  6.]
 [-3. -3. -3.]
 [ 3.  3.  3.]] 

*
 [[-1. -4. -9.]
 [28. 40. 54.]
 [28. 40. 54.]] 

/
 [[-1.        -1.        -1.       ]
 [ 0.5714286  0.625      0.6666667]
 [ 1.75       1.6        1.5      ]] 

**
 [[-1.0000000e+00  2.5000000e-01  3.7037037e-02]
 [ 1.6384000e+04  3.9062500e+05  1.0077696e+07]
 [ 2.4010000e+03  3.2768000e+04  5.3144100e+05]]


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'float32')

# Element-wise function application
B = np.exp(A)
C = np.log(B)       # Natural logarithm
D = np.tan(A)

print('A\n', A, '\n')
print('B\n', B, '\n')
print('C\n', C, '\n')
print('D\n', D)

A
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

B
 [[2.7182820e+00 7.3890557e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342877e+02]
 [1.0966332e+03 2.9809580e+03 8.1030840e+03]] 

C
 [[1.0000001 2.        3.       ]
 [4.        5.        6.       ]
 [7.        8.        9.       ]] 

D
 [[ 1.5574077  -2.1850398  -0.14254655]
 [ 1.1578213  -3.380515   -0.29100618]
 [ 0.871448   -6.799711   -0.45231566]]


In [32]:
A = np.array([2, 3, 0])
B = np.array([0, 1, -1])
print(np.dot(A, B), '\n')

A = np.ones((3, 4))
B = np.ones((4, 5))
C = np.dot(A, B)
print(C)
print('A:', A.shape, ' B:', B.shape, ' C:', C.shape)

3 

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
A: (3, 4)  B: (4, 5)  C: (3, 5)


In [88]:
A = np.random.randint(low=-99, high=100, size=(4, 5), dtype=np.int8)

print('A\n', A, '\n')

print('Min\n', np.min(A, 0))
print('Max\n', np.max(A, 0))
print('Mean\n', np.mean(A, 0))
print('Average\n', np.average(A, 0))
print('Sum\n', np.sum(A, 0))


A
 [[ 49 -23 -38  61 -14]
 [-47 -68  51  48  35]
 [-76 -89 -26 -41  43]
 [-79 -50 -71  87  42]] 

Min
 [-79 -89 -71 -41 -14]
Max
 [ 49 -23  51  87  43]
Mean
 [-38.25 -57.5  -21.    38.75  26.5 ]
Average
 [-38.25 -57.5  -21.    38.75  26.5 ]
Sum
 [-153 -230  -84  155  106]


In [85]:
A = np.random.rand(3, 4)        # From [0.0, 1.0), MATLAB-style syntax
B = np.random.random((3, 3))    # From [0.0, 1.0), Pythonic style
b = np.random.random()          # Scalar from [0.0, 1.0)

C = np.random.uniform(low=2.0, high=8.0, size=(3, 3))   # From [low, high)
C2 = np.random.uniform(low=3, high=5, size=(3, 3)).astype(np.float64)
c = np.random.uniform(low=4.0, high=8.0)                # Scalar from [low, high)

D = np.random.randn(3, 3)       # From standard normal distribution (mean=0, var=1)
d = np.random.randn()           # Scalar from standard normal distribution (mean=0, var=1)

E = np.random.randint(low=-9, high=10, size=(3, 4), dtype=np.int8)  #From [low, high)
e = np.random.randint(10, 50, dtype=np.int16)   # Scalar from [low, high)

print(A, '\n\n', B, '\n\n', C, '\n\n', D, '\n\n', E, '\n')
print(b, c, d, e)

[[0.73140298 0.41027454 0.31679897 0.45626566]
 [0.81388246 0.11375993 0.97059461 0.71690039]
 [0.41798775 0.54664875 0.70620197 0.45771264]] 

 [[0.20688299 0.24517319 0.28514098]
 [0.0023162  0.89996626 0.97951846]
 [0.46008004 0.93029449 0.39767684]] 

 [[6.77950092 6.84763816 2.67108209]
 [4.64380563 6.05774511 7.21379435]
 [5.01916985 4.74011609 3.99977614]] 

 [[ 0.57736378 -1.24328489  0.87617073]
 [-0.94204656  1.63179724 -0.6628547 ]
 [ 0.22882957 -1.62098061 -0.77988601]] 

 [[ 6  6  8 -6]
 [ 8 -2  3 -6]
 [-7  1 -2  6]] 

0.17752652877202268 5.022030467685964 -0.6639680739532445 23


In [123]:
A = np.random.uniform(low=-10, high=10, size=(4, 4))
B = np.linalg.inv(A)            # Inverse matrix
print(B)
print(np.round(np.dot(A, B)), '\n')

d = np.linalg.det(A)            # Determinant
print("det = ", d, '\n')

vals, vecs = np.linalg.eig(A)     # Eigenvalues and eigenvectors
print("Eigenvalues:", vals)


[[-0.04995023  0.11073855 -0.02578654  0.01968989]
 [ 0.08620952 -0.00237393  0.08289666 -0.02593574]
 [ 0.04215906  0.04489908 -0.07083887  0.09008315]
 [-0.03021722  0.0815658  -0.04094447 -0.07189637]]
[[ 1. -0.  0.  0.]
 [-0.  1.  0. -0.]
 [-0.  0.  1. -0.]
 [-0.  0.  0.  1.]] 

det =  -8128.756078194414 

Eigenvalues: [ 10.28887176+0.j         -17.08057547+0.j
  -5.40496948+4.12804903j  -5.40496948-4.12804903j]
