<a href="https://colab.research.google.com/github/oleg0x/Python_libraries_examples/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

    numpy.linalg — реализует операции линейной алгебры (простое умножение векторов и матриц есть в базовом варианте);
    numpy.random — реализует функции для работы со случайными величинами;
    numpy.fft — реализует прямое и обратное преобразование Фурье.


In [48]:
def get_numeric_types_dynamically():
    """Dynamically find numeric types in NumPy 2.0+"""
    numeric_types = {
        'Integer': [],
        'Unsigned Integer': [],
        'Float': [],
        'Complex': [],
    }
    for name in dir(np):
        dtype = getattr(np, name)
        if not isinstance(dtype, type):
            continue
        if name.startswith('int'):
            numeric_types['Integer'].append(dtype)
        elif name.startswith('uint'):
            numeric_types['Unsigned Integer'].append(dtype)
        elif name.startswith('float'):
            numeric_types['Float'].append(dtype)
        elif name.startswith('complex'):
            numeric_types['Complex'].append(dtype)
    return numeric_types

get_numeric_types_dynamically()

# Also: bool, bytes, str, void

{'Integer': [numpy.int16,
  numpy.int32,
  numpy.int64,
  numpy.int8,
  numpy.int64,
  numpy.int32,
  numpy.integer,
  numpy.int64],
 'Unsigned Integer': [numpy.uint64,
  numpy.uint16,
  numpy.uint32,
  numpy.uint64,
  numpy.uint8,
  numpy.uint32,
  numpy.uint64],
 'Float': [numpy.longdouble,
  numpy.float16,
  numpy.float32,
  numpy.float64,
  numpy.floating],
 'Complex': [numpy.complex128,
  numpy.clongdouble,
  numpy.complex64,
  numpy.complexfloating]}

In [133]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')    # From lists
A

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [54]:
B = np.zeros((3, 4), 'float16')
print(B, B.dtype)
C = np.zeros_like(A, 'int8')    # The same size as A
print(C, C.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float16
[[0 0 0]
 [0 0 0]] int8


In [56]:
B = np.ones((3, 4), 'float32')
print(B, B.dtype)
C = np.ones_like(A, 'bool')     # The same size as A
print(C, C.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float32
[[ True  True  True]
 [ True  True  True]] bool


In [65]:
E = np.eye(3, dtype=np.int16)   # Identity matrix
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [66]:
beg = 2.5
end = 7
step = 0.5
B = np.arange(beg, end, step)
B

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [68]:
B = A.astype('str')             # Returns a new array
B

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [142]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')

M = A                           #Shallow copy
M[0, 1] *= 100
print("M =", M, M.dtype)
print("A =", A, A.dtype)
print(A == M, '\n')

N = A.copy()                    # Deep copy
N[0, 2] *= 100
print("N =", N, N.dtype)
print("A =", A, A.dtype)
print(A == N)

M = [[  1 200   3]
 [  4   5   6]] int32
A = [[  1 200   3]
 [  4   5   6]] int32
[[ True  True  True]
 [ True  True  True]] 

N = [[  1 200 300]
 [  4   5   6]] int32
A = [[  1 200   3]
 [  4   5   6]] int32
[[ True  True False]
 [ True  True  True]]


In [140]:
A = np.array([[1, 2, 3], [4, 5, 6]], 'int32')
print(A[0][2], A[0, 2])         # The same
print(A[1], A[1, :])            # The same
print(A[:, 1])
print("Last element:", A[-1][-1])
print("Last row:", A[-1])
print("Last column:", A[:, -1])
print("Columns in reverse order:", A[:, -1], A[:, -2], A[:, -3])

3 3
[4 5 6] [4 5 6]
[2 5]
Last element: 6
Last row: [4 5 6]
Last column: [3 6]
Columns in reverse order: [3 6] [2 5] [1 4]


In [136]:
A = np.arange(10)
print(A)
print(A[[0, 4, -1]])            # Select specified elements by index
beg = 1; end = 8; step = 2
print(A[beg:end:step])          # Select from [beg, end) with step
print(A[2:6])                   # By default, step = 1
print(A[:5], A[5:])

[0 1 2 3 4 5 6 7 8 9]
[0 4 9]
[1 3 5 7]
[2 3 4 5]
[0 1 2 3 4] [5 6 7 8 9]


In [3]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B = A[::-1]                     # From last to first
C = A[:, ::-1]                  # Take all elements, from last to first inside
print(A)
print(B)
print(C)

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]]
[[4 3 2 1]
 [8 7 6 5]]


In [160]:
A = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[False, False, True], [ True, False, True]])
A[I]

array([3, 4, 6])

In [161]:
A = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[False, True, False], [False, True, False]])      # Indexing array
A[I] = 100
A

array([[  1, 100,   3],
       [  4, 100,   6]])

In [162]:
A = np.array([[1, 2, 3], [4, 5, 6]])

I1 = np.array([[False, False, True], [True, False, True]])
I2 = np.array([[False, True, False], [False, False, True]])

B = A.copy();  C = A.copy();  D = A.copy()

B[np.logical_and(I1, I2)] = 100
C[np.logical_or(I1, I2)] = 100
D[np.logical_not(I1)] = 100

print('B:\n', B)
print('\nC:\n', C)
print('\nD:\n', D)

B:
 [[  1   2   3]
 [  4   5 100]]

C:
 [[  1 100 100]
 [100   5 100]]

D:
 [[100 100   3]
 [  4 100   6]]


In [170]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('A before:\n', A)

I = A > 3
print('I:\n', I)

A[np.logical_or(A < 2, A > 4)] = 100
print('A after:\n', A)

A before:
 [[1 2 3]
 [4 5 6]]
I:
 [[False False False]
 [ True  True  True]]
A after:
 [[100   2   3]
 [  4 100 100]]


In [176]:
A = np.arange(24)
B = A.reshape(4, 6)             # 4 * 6 = 24
C = A.reshape(2, 3, 4)          # 2 * 3 * 4 = 24
# These are different representations of the same data
C[0, 0, 0] = -1
print('A:\n', A)
print('\nB:\n', B)
print('\nC:\n', C)

A:
 [-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

B:
 [[-1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

C:
 [[[-1  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [194]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.reshape(3, 2))
print(A.reshape(6, 1))
print(A.reshape(1, 6))
print(A.ravel())

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


In [199]:
A = np.arange(24)
B = A.reshape(-1, 6)            # -1 means "calculate automatically"
C = A.reshape(4, -1, 2)         # -1 means "calculate automatically"
print(B.shape, C.shape)

(4, 6) (4, 3, 2)


In [200]:
A = np.arange(12)
B = A.reshape(3, 4)
print(B)
print("Size:", B.size)
print("Dim:", B.ndim)
print("Shape:", B.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Size: 12
Dim: 2
Shape: (3, 4)


In [213]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.T                         # Matrix transposition
B = np.transpose(A)             # Matrix transposition
B = np.swapaxes(A, 0, 1)
print('A:\n', A)
print('B:\n', B)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[1 4]
 [2 5]
 [3 6]]


In [32]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.stack((A, B), axis=0)        # Join arrays along a new axis
D = np.stack((A, B), axis=1)        # Join arrays along a new axis

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]] 
Shape: (2, 3, 3) 

[[[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]] 
Shape: (3, 2, 3)


In [31]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.concatenate((A, B), 0)       # Joins arrays along an existing axis
D = np.concatenate((A, B), 1)       # Joins arrays along an existing axis

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]] 
Shape: (6, 3) 

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 
Shape: (3, 6)


In [34]:
A = np.zeros((3, 3), 'int32')
B = np.ones((3, 3), 'int32')

C = np.vstack((A, B))               # Stacks arrays vertically (row-wise)
D = np.hstack((A, B))               # Stacks arrays horizontally (column-wise)

print(C, '\nShape:', C.shape, '\n')
print(D, '\nShape:', D.shape, '\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]] 
Shape: (6, 3) 

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 
Shape: (3, 6) 

