<a href="https://colab.research.google.com/github/oleg0x/Python_libraries_examples/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)
print(torch.__all__)

2.6.0+cu124
['BoolStorage', 'BoolTensor', 'ByteStorage', 'ByteTensor', 'CharStorage', 'CharTensor', 'DoubleStorage', 'DoubleTensor', 'FloatStorage', 'FloatTensor', 'GradScaler', 'IntStorage', 'IntTensor', 'LongStorage', 'LongTensor', 'ShortStorage', 'ShortTensor', 'SymBool', 'SymFloat', 'SymInt', 'Tensor', 'TypedStorage', 'UntypedStorage', 'are_deterministic_algorithms_enabled', 'autocast', 'chunk', 'compile', 'cond', 'enable_grad', 'export', 'get_default_device', 'get_deterministic_debug_mode', 'get_device_module', 'get_float32_matmul_precision', 'get_rng_state', 'inference_mode', 'initial_seed', 'is_deterministic_algorithms_warn_only_enabled', 'is_storage', 'is_tensor', 'is_warn_always_enabled', 'load', 'lobpcg', 'manual_seed', 'matmul', 'no_grad', 'rand', 'randn', 'save', 'seed', 'set_default_device', 'set_default_tensor_type', 'set_deterministic_debug_mode', 'set_float32_matmul_precision', 'set_printoptions', 'set_rng_state', 'set_warn_always', 'split', 'stack', 'sym_float', 'sym_f

In [3]:
all_dtypes = [str(getattr(torch, name)) for name in dir(torch)
              if isinstance(getattr(torch, name), torch.dtype)]
all_dtypes_unique = set(all_dtypes)

bools = [t for t in all_dtypes_unique if ".bool" in t]
print("Bool:", bools)
ints = [t for t in all_dtypes_unique if ".int" in t]
print("Signed Int:", ints)
uints = [t for t in all_dtypes_unique if ".uint" in t]
print("Unsigned Int:", uints)
floats = [t for t in all_dtypes_unique if "float" in t]
print("Float:", floats)
complexes = [t for t in all_dtypes_unique if ".complex" in t]
print("Complex:", complexes)

print('\n', all_dtypes_unique)

Bool: ['torch.bool']
Signed Int: ['torch.int4', 'torch.int3', 'torch.int8', 'torch.int5', 'torch.int7', 'torch.int1', 'torch.int6', 'torch.int64', 'torch.int16', 'torch.int2', 'torch.int32']
Unsigned Int: ['torch.uint1', 'torch.uint7', 'torch.uint64', 'torch.uint2', 'torch.uint32', 'torch.uint16', 'torch.uint5', 'torch.uint4', 'torch.uint6', 'torch.uint3', 'torch.uint8']
Float: ['torch.float32', 'torch.float8_e5m2fnuz', 'torch.bfloat16', 'torch.float8_e4m3fn', 'torch.float16', 'torch.float64', 'torch.float8_e4m3fnuz', 'torch.float8_e5m2']
Complex: ['torch.complex32', 'torch.complex64', 'torch.complex128']

 {'torch.quint4x2', 'torch.float32', 'torch.int4', 'torch.bits16', 'torch.float8_e5m2fnuz', 'torch.complex32', 'torch.complex64', 'torch.int3', 'torch.int8', 'torch.int5', 'torch.uint1', 'torch.int7', 'torch.quint2x4', 'torch.bool', 'torch.int1', 'torch.quint8', 'torch.bits1x8', 'torch.uint7', 'torch.bfloat16', 'torch.uint64', 'torch.int6', 'torch.uint2', 'torch.uint32', 'torch.int64

In [4]:
# Tensor filled with uninitialized data
a = torch.empty(1)                  # Single-element tensor
print(a)
val = a.item()                      # Value of that tensor
print(val, '\n')

b = torch.empty(5)                  # Vector of lenght 5 as tensor
print(b, '\n')

c = torch.empty(3, 4)               # 3x4 matrix as tensor
print(c, '\n')

d = torch.empty(2,2,2,3)            # 4 dim tensor
print(type(d))

tensor([4.7851e+22])
4.7851115335980964e+22 

tensor([1.2085e+02, 0.0000e+00, 1.7835e-22, 4.3065e-41, 8.9683e-44]) 

tensor([[0.0000e+00, 0.0000e+00, 2.0812e+02, 0.0000e+00],
        [2.8723e+01, 0.0000e+00, 5.9898e-27, 4.3063e-41],
        [1.4013e-45, 0.0000e+00, 5.6052e-45, 0.0000e+00]]) 

<class 'torch.Tensor'>


In [5]:
a = torch.zeros(2, 4, dtype=torch.int16)        # Tensor filled with value 0
print(a, '\n')

b = torch.ones(2, 4)                            # Tensor filled with value 1
c = torch.ones(5, dtype=torch.bool)             # Tensor filled with 'True'
print(b)
print(c, '\n')

e = torch.eye(3, 3)
print(e, '\n')

data = [[1, 2, 3],[4, 5, 6]]
x_data = torch.tensor(data)                     # Tensor from list
print(x_data)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16) 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([True, True, True, True, True]) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) 

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
x1 = torch.rand(3, 5, dtype=torch.bfloat16)         # Tensor filled with random numbers from a uniform distribution on [0, 1)
print(x1, '\n')

x2 = torch.randn(2, 3, dtype=torch.float32)         # Tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (standard normal distribution).
print(x2)
print(x2.dtype, '\n')

y = torch.randint(low=1, high=100, size=(3, 5), dtype=torch.uint8)      # Tensor filled with random integers generated uniformly from [low, high)
print(y)
print(y.dtype)

tensor([[0.9492, 0.7031, 0.5312, 0.8164, 0.9297],
        [0.2734, 0.9492, 0.0312, 0.1562, 0.8281],
        [0.4688, 0.5352, 0.0742, 0.4961, 0.0508]], dtype=torch.bfloat16) 

tensor([[-0.1142,  1.0412, -1.3919],
        [ 1.0939,  2.1491, -0.3756]])
torch.float32 

tensor([[98, 87, 35, 69, 43],
        [90, 10, 40, 17, 17],
        [43, 81, 40, 15, 47]], dtype=torch.uint8)
torch.uint8


In [7]:
x = torch.empty(3, 3)

x.zero_()
print(x)

x.fill_(42)
print(x)

x.random_(10, 100)
print(x)

x.uniform_()
print(x)

x.normal_()
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])
tensor([[63., 53., 97.],
        [89., 70., 49.],
        [38., 18., 98.]])
tensor([[0.3429, 0.3037, 0.0852],
        [0.0217, 0.5570, 0.1226],
        [0.9898, 0.0880, 0.6225]])
tensor([[ 0.9013, -0.2936,  0.4873],
        [-1.3071, -1.1541,  0.6366],
        [-0.5746,  0.7408, -0.1050]])


In [8]:
print(y.dim())
print(y.size(), y.shape)

2
torch.Size([3, 5]) torch.Size([3, 5])


In [9]:
t = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(t, '\n')
print(f"First row: {t[0, :]} {t[0]}")
print(f"First column: {t[:, 0]}")
print(f"Last row: {t[-1, :]} {t[-1]}")
print(f"Last column: {t[:, -1]}")

t[..., 2] = 0           # ... can be used instead of :
t[1, ...] = 0           # ... can be used instead of :
t[1, 2] = 42            # Access one element
print(t)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]) 

First row: tensor([1, 2, 3, 4]) tensor([1, 2, 3, 4])
First column: tensor([ 1,  5,  9, 13])
Last row: tensor([13, 14, 15, 16]) tensor([13, 14, 15, 16])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  2,  0,  4],
        [ 0,  0, 42,  0],
        [ 9, 10,  0, 12],
        [13, 14,  0, 16]])


In [10]:
x = torch.randint(-5, 6, (2, 2))
y = torch.randint(-5, 6, (2, 2))
print(x)
print(y, '\n')

# Element-wise operations
z1 = x + y;  z1 = torch.add(x, y)
z2 = x - y;  z2 = torch.sub(x, y)
z3 = x * y;  z3 = torch.mul(x, y)
z4 = x / y;  z4 = torch.div(x, y)

print("Add:", z1)
print("Sub:", z2)
print("Mul:", z3)
print("Div:", z4)

y.add_(x)    # y += x
y.sub_(x)    # y -= x
y.mul_(x)    # y *= x
#y.div_(x)    # y /= x

# Operations: +, +=, -, -=, *, *=, /, /=, @

tensor([[-1, -4],
        [-2, -3]])
tensor([[ 1,  0],
        [ 4, -5]]) 

Add: tensor([[ 0, -4],
        [ 2, -8]])
Sub: tensor([[-2, -4],
        [-6,  2]])
Mul: tensor([[-1,  0],
        [-8, 15]])
Div: tensor([[-1.0000,    -inf],
        [-0.5000,  0.6000]])


tensor([[-1,  0],
        [-8, 15]])

In [13]:
x = torch.randint(-5, 6, (2, 3), dtype=torch.int32)
y = torch.randint(-5, 6, (3, 2), dtype=torch.int32)
print(x)
print(y, '\n')

# Matrix multiplication
z1 = x @ y
z2 = x.mm(y)
z3 = x.matmul(y)
z4 = torch.empty(2, 2, dtype=torch.int32)
torch.matmul(x, y, out=z4)
print(z1, '\n')
torch.testing.assert_close(z1, z2)
torch.testing.assert_close(z1, z3)
torch.testing.assert_close(z1, z4)

v = torch.randint(-5, 6, (3,), dtype=torch.int32)
z1 = x.mv(v)                    # Multiply matrix and vector
z2 = torch.mv(x, v)             # Multiply matrix and vector
print(v)
print(z1, '\n')
torch.testing.assert_close(z1, z2)

u = torch.randint(-5, 6, (3,), dtype=torch.int32)
z1 = v.dot(u)                   # Dot product of two vectors
z2 = torch.dot(v, u)
print(u)
print(z1)
torch.testing.assert_close(z1, z2)

tensor([[-3,  0,  0],
        [ 4, -4,  1]], dtype=torch.int32)
tensor([[ 5,  0],
        [ 5,  3],
        [-4, -4]], dtype=torch.int32) 

tensor([[-15,   0],
        [ -4, -16]], dtype=torch.int32) 

tensor([-5,  5, -2], dtype=torch.int32)
tensor([ 15, -42], dtype=torch.int32) 

tensor([-3,  3, -5], dtype=torch.int32)
tensor(40, dtype=torch.int32)


In [14]:
x = torch.randn(3, 4)
print(x, '\n')

z = x.abs()
z = torch.abs(x)
x.abs_()
print(z)

z = x.exp()
z = torch.exp(x)
x.exp_()
print(z)

z = x.log()
z = torch.log(x)
x.log_()
print(z)

tensor([[ 0.0331, -1.3488, -0.7913, -0.9413],
        [-1.8024,  0.0121, -0.3931, -0.8201],
        [ 0.5513, -1.5801, -1.9916, -0.1655]]) 

tensor([[0.0331, 1.3488, 0.7913, 0.9413],
        [1.8024, 0.0121, 0.3931, 0.8201],
        [0.5513, 1.5801, 1.9916, 0.1655]])
tensor([[1.0337, 3.8526, 2.2064, 2.5634],
        [6.0645, 1.0122, 1.4816, 2.2707],
        [1.7355, 4.8555, 7.3275, 1.1800]])
tensor([[0.0331, 1.3488, 0.7913, 0.9413],
        [1.8024, 0.0121, 0.3931, 0.8201],
        [0.5513, 1.5801, 1.9916, 0.1655]])


In [15]:
x = torch.randn(3, 4)
print(x)

z = x.t()
z = torch.t(x)
#x.t_()
print(z)

m0 = x.mean(0)
m = x.mean()
s = x.std()
v = x.var()
print(m.item(), s.item(), v.item())

tensor([[-0.1808, -0.1792, -0.7453, -1.2639],
        [-1.5805, -0.9060, -0.0443, -0.3282],
        [-1.3062, -0.0144, -1.1739,  0.7442]])
tensor([[-0.1808, -1.5805, -1.3062],
        [-0.1792, -0.9060, -0.0144],
        [-0.7453, -0.0443, -1.1739],
        [-1.2639, -0.3282,  0.7442]])
-0.5815389752388 0.689302384853363 0.47513777017593384


In [16]:
x = torch.randint(-5, 6, (2, 3))
print(x)

s1 = x.sum()
s2 = x.prod()
s3 = x.max()
s4 = x.min()
print(s1, s2, s3, s4)

tensor([[-3,  1,  0],
        [-5,  5, -2]])
tensor(-4) tensor(0) tensor(5) tensor(-5)


In [17]:
x = x = torch.randint(-5, 6, (3, 4), dtype=torch.int32)    # 3 x 4 = 12
x1 = x.view(2, 6)           # 2 x 6 = 12
x2 = x.view(12)             # 12
print(x)
print(x1)
print(x2, '\n')

x = torch.arange(16)        # Tensor filled with 0, 1, ..., 15
y = x.view(2, -1)           # -1 will be changed to 8, 2 x 8 = 16
print('\n', x)
print(y)

tensor([[-4, -5,  0,  1],
        [ 0, -4, -4,  4],
        [ 5,  0, -4,  2]], dtype=torch.int32)
tensor([[-4, -5,  0,  1,  0, -4],
        [-4,  4,  5,  0, -4,  2]], dtype=torch.int32)
tensor([-4, -5,  0,  1,  0, -4, -4,  4,  5,  0, -4,  2], dtype=torch.int32) 


 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])


In [18]:
import numpy as np
a = np.random.randint(0, 10, (2 ,3))
print(a, '\n')

x = torch.from_numpy(a)         # Data is not being copied
x *= 2
print(x)
print(a, '\n')

b = x.numpy()
print(b)

[[8 3 9]
 [5 5 5]] 

tensor([[16,  6, 18],
        [10, 10, 10]])
[[16  6 18]
 [10 10 10]] 

[[16  6 18]
 [10 10 10]]


In [19]:
x = torch.rand(1, 3)
x = x.to("cpu")                         # Move tensor to CPU device
print(x)
x = x.to("cuda")                        # Move tensor to GPU device
print(x)

dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
y = torch.rand(1, 3).to(dev)            # Move tensor to GPU, if available
print(y)

z = torch.rand(1, 3, device="cuda")     # Create tensor on GPU
print(z)

print(z.is_cuda)
print(x.get_device())

with torch.cuda.device(0):
    a = torch.cuda.FloatTensor(5)

tensor([[0.0801, 0.9230, 0.1197]])
tensor([[0.0801, 0.9230, 0.1197]], device='cuda:0')
tensor([[0.0440, 0.2097, 0.7291]], device='cuda:0')
tensor([[0.0834, 0.5239, 0.9015]], device='cuda:0')
True
0


/tmp/ipython-input-19-1908805501.py:18: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  a = torch.cuda.FloatTensor(5)


In [20]:
x = torch.rand(1, 3)
print(x.is_pinned())

x.pin_memory()              # Copies tensor to pinned memory, if it's not already pinned
print(x.is_pinned())

False
False


In [21]:
x = torch.randn(3, requires_grad=True)
print(x)                    # Created by the user, grad_fn is None
print(x.grad_fn, '\n')

y = 2*x + 3                 # y is created as a result of operations, so it has a grad_fn
print(y)
print(y.grad_fn)

tensor([ 2.4028, -0.9883, -1.5948], requires_grad=True)
None 

tensor([ 7.8056,  1.0235, -0.1897], grad_fn=<AddBackward0>)


In [22]:
a = torch.randn(2, 2)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn, '\n')

a = torch.randn(2, 2, requires_grad=True)
b = a.detach()                  # New tensor with the same content but no gradient computation
print("a.requires_grad:", a.requires_grad)
print("b.requires_grad:", b.requires_grad, '\n')

with torch.no_grad():
    b = a**2 + 1
    print(b.requires_grad)

False
True

a.requires_grad: True
b.requires_grad: False 

False


In [23]:
print(x.grad)
y.backward(x)           # backward() accumulates (!) the gradient for this tensor into .grad attribute
print(x.grad)           # dy/dx

None
tensor([ 4.8056, -1.9765, -3.1897])
