<a href="https://colab.research.google.com/github/oleg0x/Python_libraries_examples/blob/main/scipy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy

print(scipy.__all__)

['cluster', 'constants', 'datasets', 'differentiate', 'fft', 'fftpack', 'integrate', 'interpolate', 'io', 'linalg', 'ndimage', 'odr', 'optimize', 'signal', 'sparse', 'spatial', 'special', 'stats', 'LowLevelCallable', 'test', 'show_config', '__version__']


In [11]:
print(scipy.constants.__all__)
print(scipy.constants.g)
print(scipy.constants.pi)

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_constant', 'h', 'hbar', 'hectare', 'hecto', 'horsepower', 'hour', 'hp', 'inch', 'k', 'kgf', 'kibi', 'kilo', 'kilogram_force', 'kmh', 'knot', 'lambda2nu', '

In [27]:
# Recomendation: Use scipy.linalg instead of numpy.linalg
from scipy import linalg

A = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
print(A, '\n')

d = linalg.det(A)
print(d, '\n')

B = linalg.inv(A)
print(B)

[[1 3 5]
 [2 5 1]
 [2 3 8]] 

-25.000000000000004 

[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]


In [32]:
from scipy import linalg

A = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
print(A, '\n', b, '\n')

x = np.linalg.solve(A, b)           # Fast solving a linear system Ax = b
print(x, '\n')

print(A @ x - b)                    # Check

[[1 2]
 [3 4]] 
 [[5]
 [6]] 

[[-4. ]
 [ 4.5]] 

[[0.]
 [0.]]


In [28]:
from scipy import linalg

eigenvals, eigenvecs = linalg.eig(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors (as columns):\n", eigenvecs, '\n')

# Verification
for i in range(len(eigenvals)):
    v = eigenvecs[:, i]
    lambda_v = eigenvals[i] * v
    Av = A @ v                      # Matrix multiplication
    print(f"Verification for eigenpair {i+1}:")
    print("A @ v:", Av)
    print("λ * v:", lambda_v)
    print("Are they close?", np.allclose(Av, lambda_v))

Eigenvalues: [10.5540456 +0.j -0.5873064 +0.j  4.03326081+0.j]
Eigenvectors (as columns):
 [[-0.51686204 -0.94195144  0.11527992]
 [-0.32845853  0.31778071 -0.81936883]
 [-0.79054957  0.10836468  0.56155611]] 

Verification for eigenpair 1:
A @ v: [-5.4549855  -3.46656629 -8.34349626]
λ * v: [-5.4549855 +0.j -3.46656629+0.j -8.34349626+0.j]
Are they close? True
Verification for eigenpair 2:
A @ v: [ 0.55321411 -0.18663465 -0.06364327]
λ * v: [ 0.55321411-0.j -0.18663465+0.j -0.06364327+0.j]
Are they close? True
Verification for eigenpair 3:
A @ v: [ 0.464954   -3.30472818  2.26490225]
λ * v: [ 0.464954  +0.j -3.30472818+0.j  2.26490225+0.j]
Are they close? True


In [4]:
from scipy import integrate

invexp = lambda x: np.exp(-x)
z, abserr = integrate.quad(invexp, 0, np.inf)
print(z)

1.0000000000000002
